auth:
  callbackUrl: /callback
  clientsProperties:

    # sample SAML authentication
#    saml.keystorePath: conf/samlKeystore.jks
#    saml.keystorePassword: pac4j-demo-passwd
#    saml.privateKeyPassword: pac4j-demo-passwd
#    saml.identityProviderMetadataPath: conf/metadata-gsuite.xml
#    saml.maximumAuthenticationLifetime: 31536000
#    saml.serviceProviderEntityId: https://localhost:8443/callback?client_name=SAML2Client
#    saml.serviceProviderMetadataPath: sp-metadata.xml

#     sample LDAP authentication
#    ldap.type: direct
#    ldap.url: ldaps://ldap.jumpcloud.com:636
#    ldap.useStartTls: false
#    ldap.useSsl: true
#    ldap.dnFormat: uid=%s,ou=Users,o=58cb8e42876d97bd3e2092d6,dc=jumpcloud,dc=com
#    ldap.usersDn: ou=Users,o=58cb8e42876d97bd3e2092d6,dc=jumpcloud,dc=com
#    ldap.principalAttributeId: uid
#    ldap.principalAttributes: mail
#    ldap.enhanceWithEntryResolver: false

     anonymous: fakevalue
     directBasicAuthClient.authenticator: rest
     rest.url: https://dashbase.io/login/basic
     formClient.loginUrl: loginRest
     formClient.authenticator: rest

  authorizers:
    mustBeAuth:
      class: org.pac4j.core.authorization.authorizer.IsAuthenticatedAuthorizer
      redirectionUrl: /
    mustBeAnon:
      class: org.pac4j.core.authorization.authorizer.IsAnonymousAuthorizer
      redirectionUrl: /

# defines the url that user will be taking after authentication completes.
dashbaseWebURL: ${WEB_URL}

# authorization tokens are stored in this file, make sure it's protected on your server.
database:
  driverClass: org.sqlite.JDBC
  url: "jdbc:sqlite:../auth/auth.db"
  properties:
    charSet: UTF-8

# SAML requires HTTPS
# unless you want user's to see a warning message on their browsers, setup an internal SSL provider inside your network
server:
  applicationContextPath: /
  adminContextPath: /admin
  applicationConnectors:
  - type: http
    port: ${PORT}
  # - keyStorePassword: awesomedashbase
  #   keyStorePath: /data/auth/keystore.jks
  #   type: https
  #   port: ${HTTPS_PORT}
    # validateCerts: false
  adminConnectors:
  - type: http
    port: ${ADMINPORT}
  # - keyStorePassword: awesomedashbase
  #   keyStorePath: /data/auth/keystore.jks
  #   type: https
  #   port: ${HTTPS_ADMINPORT}
  #   validateCerts: false

logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: ../logs/dashbase-auth.log
      archive: true
      archivedLogFilenamePattern: ../logs/dashbase-auth-%d.log
      archivedFileCount: 9
      timeZone: UTC
