dashbase:
  baseDir: /mnt/dashbase/index/regex # requires write permissions

  cluster:
    name: example-regex
    url: ${ZOOKEEPER_URL}

  firehose:
    type: file
    params:
      file: ../sample-data/nginx.log # this needs to be the path to the sample data on the remote host
      numReplications: 1000000

  indexer:
    maxIndexingDelayInSec: 5

  parser:
    type: regex
    params:
      patterns:
        regex: "^([\\d.]+) (\\S+) (\\S+) (\\S+) \\[([\\w:/]+\\s[+\\-]\\d{4})\\] \"(.+?)\" (\\d{3}) (\\d+) (\\d+) \"([^\"]+)\" \"([^\"]+)\""
        timeFormat: now
        schema:
          - name: host
            type: meta
          - type: '-'
          - type: '-'
          - type: '-'
          - type: time
          - name: request
            type: text
          - name: response
            type: meta
          - name: bytesSent
            type: numeric
          - type: '-'
          - type: '-'
          - name: agent
            type: text

  retention:
    numDays: .02 # number of days before expiring time-slices. e.g. 0.5 days

server:
  applicationConnectors:
  - type: http
    port: ${PORT}
  adminConnectors:
  - type: http
    port: ${ADMINPORT}

metrics:
  reporters:
    - type: dashbase
      url: ${MONITOR_URL} # host port of monitor
      includes:
        - ^jvm.*$
        - ^dashbase.*$
      useRegexFilters: true
      frequency: 5 seconds

logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: ../logs/nginx-regex.log
        archive: true
        archivedLogFilenamePattern: ../logs/nginx-regex-%d.log
        archivedFileCount: 7
        timeZone: UTC
      - type: dashbase
        url: ${MONITOR_URL} # host port of monitor
        timeZone: UTC
