dashbase:
  baseDir: /mnt/dashbase/index/json # requires write permissions

  cluster:
    url: zk://${ZOOKEEPER_URL}/dashbase/test/example-json

  firehose:
    type: file
    params:
      file: ../sample-data/nginx.json # this needs to be the path to the sample data on the remote host
      numReplications: 1000000

  indexer:
    maxBufferDelayInSec: 5

  parser:
    type: json
    params:
      pattern:
        timeFormat: now
        schema:
          - name: host
            type: meta
          - name: request
            type: text
          - name: responseCode
            type: meta
          - name: numBytes
            type: numeric
          - name: agent
            type: text

  retention:
    numDays: .02 # number of days before expiring time-slices. e.g. 0.5 days

server:
  applicationContextPath: /
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: ${PORT}
  adminConnectors:
    - type: http
      port: ${ADMINPORT}

metrics:
  reporters:
    - type: dashbase
      url: ${MONITOR_URL} # host port of monitor
      includes:
        - ^jvm.*$
        - ^dashbase.*$
      useRegexFilters: true
      frequency: 5 seconds

logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: ../logs/nginx-json.log
        archive: true
        archivedLogFilenamePattern: ../logs/nginx-json-%d.log
        archivedFileCount: 7
        timeZone: UTC
      - type: dashbase
        url: ${MONITOR_URL} # host port of monitor
        timeZone: UTC
