version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/dashbase-quickstart
    steps:
      - run:
          name: Install dependencies
          command: pip install awscli --upgrade --user
      - run:
          name: Create Package
          command: tar -zcvf quickstart.tar.gz --exclude="*.git*" --exclude="*.circle*" --exclude="*.tar.gz" .
      - run:
          name: Sync Package to S3
          command: aws s3 cp quickstart.tar.gz s3://dashbase-public/quickstart/
      - run:
          name: Update template_names.json file
          command: |
              echo '{"names":["quickstart"]} > template_names.json
              aws s3 cp template_names.json s3://dashbase-public/