version: 2
jobs:
   build:
     docker:
       - image: circleci/python:2.7.13
     steps:
       - checkout
       - run:
          name: Install dependencies
          command: pip install awscli --upgrade --user
       - run:
          name: Copy and package configs
          command: |
            mkdir ~/dashbase-quickstart
            cp -R . ~/dashbase-quickstart/
            tar -zcvf ~/dashbase-quickstart.tar.gz --exclude="*.git*" ~/dashbase-quickstart
       - run:
          name: Sync to AWS S3 bucket
          command: aws s3 sync ~/dashbase-quickstart.tar.gz s3://dashbase-public/quickstart/
       - run:
          name: Update template_names.json
          command: |
            echo '{"names":["quickstart"]} > template_names.json
            aws s3 sync template_names.json s3://dashbase-public/

'