version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/dashbase-quickstart
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: pip install awscli --upgrade --user
      - run:
          name: Create Package
          command: tar -zcvf ~/quickstart.tar.gz --exclude="*.git*" --exclude="*.circle*" -C ~/ dashbase-quickstart
      - run:
          name: Sync Package to S3
          command: aws s3 cp ~/quickstart.tar.gz s3://dashbase-public/quickstart/

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
