version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - run:
          name: Install dependencies
          command: pip install awscli --upgrade --user
      - run:
          name: Copy Configs
          command: |
              cd ~/
              mkdir dashbase-quickstart
              cp -R project/ dashbase-quickstart/ 
      - run:
          name: Create Package
          command: |
              cd ~/
              tar -zcvf quickstart.tar.gz --exclude="*.git*" --exclude="*.circle*" dashbase-quickstart
      - run:
          name: Sync Package to S3
          command: |
              cd ~/
              aws s3 sync quickstart.tar.gz s3://dashbase-public/quickstart/
      - run:
          name: Update template_names.json file
          command: |
              echo '{"names":["quickstart"]} > template_names.json
              aws s3 sync template_names.json s3://dashbase-public/