cluster:
  url: zk://${ZOOKEEPER_URL}/dashbase

license: dashbase-license.yml

server:
  applicationConnectors:
    - type: http
      port: ${PORT}
  applicationContextPath: /
  adminContextPath: /admin
  adminConnectors:
      - type: http
        port: ${ADMINPORT}

metrics:
  reporters:
    - type: dashbase
      url: ${MONITOR_URL} # host port of monitor
      meta:
        name: example-api
        type: dashbase-api
      includes:
        - ^jvm.*$
        - ^dashbase.*$
      useRegexFilters: true
      frequency: 5 seconds

logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: ../logs/dashbase-api.log
        archive: true
        archivedLogFilenamePattern: ../logs/dashbase-api-%d.log
        archivedFileCount: 7
        timeZone: UTC
      - type: dashbase
        url: ${MONITOR_URL}  # host port of monitor
        meta:
          name: example-api
          type: dashbase-api
        timeZone: UTC
